### ISSUE TITLE
Traceback on Ubuntu 18.04 with LANG set to es_PY.utf8

### ISSUE THREAD

**Issue by quozl** [sugarlabs/memorize-activity#26]
```
Traceback (most recent call last):
  File "/usr/bin/sugar-activity", line 5, in <module>
    activityinstance.main()
  File "/usr/lib/python2.7/dist-packages/sugar3/activity/activityinstance.py", line 219, in main
    instance = create_activity_instance(activity_constructor, activity_handle)
  File "/usr/lib/python2.7/dist-packages/sugar3/activity/activityinstance.py", line 50, in create_activity_instance
    activity = constructor(handle)
  File "/usr/share/sugar/activities/Memorize.activity/activity.py", line 113, in __init__
    self.createcardpanel = createcardpanel.CreateCardPanel(self.game)
  File "/usr/share/sugar/activities/Memorize.activity/createcardpanel.py", line 116, in __init__
    self.cardeditor1 = CardEditor(self._game, 1)
  File "/usr/share/sugar/activities/Memorize.activity/createcardpanel.py", line 368, in __init__
    self.usespeak.set_palette(SpeakPalette(self))
  File "/usr/share/sugar/activities/Memorize.activity/createcardpanel.py", line 513, in __init__
    self.face = speak.face.View()
  File "/usr/share/sugar/activities/Memorize.activity/speak/face.py", line 91, in __init__
    self.status = Status()
  File "/usr/share/sugar/activities/Memorize.activity/speak/face.py", line 44, in __init__
    self.voice = voice.defaultVoice()
  File "/usr/share/sugar/activities/Memorize.activity/speak/voice.py", line 160, in defaultVoice
    voices = allVoices()
  File "/usr/share/sugar/activities/Memorize.activity/speak/voice.py", line 126, in allVoices
    _allVoices['English'] = _allVoices['English (America)']
KeyError: 'English (America)'
```

Caused by https://github.com/sugarlabs/memorize-activity/commit/55dd54248fa6841bf41f45503d12d31d88192e04.

May also be fixed by [port to sugar3.speech](https://github.com/sugarlabs/memorize-activity/issues/8) for which we have a [pull request in progress](https://github.com/sugarlabs/memorize-activity/pull/25).

**Comment by quozl** [comment]
Was not fixed by 0728ec407a62fa3a3019cacdd4813b36b84d9e17 ("Port to sugar3.speech").
